name: OpenWrt Custom GL.Inet GL-MT6000 (Flint 2) Release

permissions:
  contents: write

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0'

env:
  REPO_URL: https://github.com/pesa1234/openwrt.git
  REPO_BRANCH: next-r4.5.36.rss.mtk
  OpenWRTDevice: Flint2_GL-MT6000
  CONFIG_FILE: config.openwrt-custom-master
  TZ: Europe/Kyiv


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@main

    - name: Free up disk space
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get clean
        df -h


    - name: Set up OpenWrt Environment
      run: |
        git clone --branch $REPO_BRANCH $REPO_URL


    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          clang \
          flex \
          bison \
          g++ \
          gawk \
          gcc-multilib \
          g++-multilib \
          gettext \
          git \
          libncurses-dev \
          libssl-dev \
          python3-distutils \
          rsync \
          swig \
          unzip \
          zlib1g-dev \
          file \
          wget \
          llvm \
          libpcre3 \
          libpcre3-dev

    - name: Display contents of .config start
      run:  |
        cat $GITHUB_WORKSPACE/$CONFIG_FILE

    - name: Update & install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load .config
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config

    - name: Display contents of .config
      run:  |
        cd openwrt
        cat .config

    - name: make defconfig
      run: |
        cd openwrt
        make defconfig

    - name: Download package sources
      run: |
        cd openwrt
        make download V=s

    - name: Build target images
      run: |
        cd openwrt
        make -j $(($(nproc)+1)) V=s || \
        make V=s

    - name: Organize files
      id: organize
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "NOW=$(date +%F-%H%M)" >> $GITHUB_ENV
        cp $PWD/version.buildinfo $GITHUB_WORKSPACE/version.buildinfo

    - name: Extract version information from version.buildinfo
      run: >-
        echo "BUILDINFO=$(cat $PWD/version.buildinfo)"
        >> $GITHUB_ENV

    - name: build RelTag
      id: BuildRelTag
      run: |
        echo "RelTag=${{ env.NOW }}_Pre_${{ env.OpenWRTDevice }}_@(${{ env.BUILDINFO }})" >> $GITHUB_ENV

    - name: Upload firmware to github
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_firmware-${{ env.OpenWRTDevice }}-${{ env.NOW }}
        path: ${{ env.FIRMWARE }}

    - name: Create a release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: True
        title: "${{ env.RelTag }}"
        automatic_release_tag: "${{ env.BUILDINFO }}"
        files: |
          ${{ env.FIRMWARE }}/*sysupgrade.bin
          ${{ env.FIRMWARE }}/*.buildinfo
          ${{ env.FIRMWARE }}/*.manifest
          ${{ env.FIRMWARE }}/sha256sums
